---
title: "Scrap_Paper"
author: "Drew Shives"
date: "9/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
```

```{r}
sqrt(sum((c(90, 80, 70) - 80) ^ 2) / 3)
```

```{r}
sd(c(90, 80, 70))
```

```{r}
x = c(5, 10, 15, 20, 25)

mean(x)

sqrt(sum((x - mean(x)) ^ 2) / length(x))
```

```{r}
x = c(100, 80, 60)

mean(x)

sqrt(sum((x - mean(x)) ^ 2) / length(x))

(100 - mean(x)) / (sqrt(sum((x - mean(x)) ^ 2) / length(x)))
```

```{r}
x = c(90, 80, 70)

mean(x)

sqrt(sum((x - mean(x)) ^ 2) / length(x))

(90 - mean(x)) / (sqrt(sum((x - mean(x)) ^ 2) / length(x)))
```

```{r}
(0.8 * 0.1) / ((0.8 * 0.1) + (0.1 * 0.9))

(0.8 * 0.1)

((0.8 * 0.1) + (0.1 * 0.9))
```

```{r}
(0.2 * 0.01) / ((0.2 * 0.01) + (0.9 * 0.99))

(0.2 * 0.01)

((0.2 * 0.01) + (0.9 * 0.99))
```

```{r}
(0.9 * 0.2) / ((0.9 * 0.2) + (0.4 * 0.8))

(0.9 * 0.2)

((0.9 * 0.2) + (0.4 * 0.8))
```

Write a for loop to print the even numbers from 1 to 100.

```{r}
x <- 1:100
for(i in x) {
  if((i %% 2 == 0) == TRUE) {
    print(i)
  }
}
```

```{r}
evens <- c()
for(i in x) {
  if((i %% 2 == 0) == TRUE) {
    evens <- c(evens, i)
  }
}

print(evens)
```

```{r}
(20/40) * (20/40)
(12/40)
```

```{r}
0.5 * 0.5
```

```{r}
((0.98) * (0.0002)) / (((0.98) * (0.0002)) + ((0.02) * (0.9998)))
```

```{r}
((0.96) * (0.02)) / (((0.96) * (0.02)) + ((0.15) * (0.98)))
```

```{r}
x <- c(2, 5, 6, 6, 7, 7, 10, 13, 7)

mean(x)
```

```{r}
x <- c(-7, 4, 3, -2, 2)
mean(x)
sum((x - mean(x)) ^ 2) / length(x)
sqrt(sum((x - mean(x)) ^ 2) / length(x))
sum((x - mean(x)) ^ 3) / (length(x) * (sqrt((sum((x - mean(x)) ^ 2) / length(x))) ^ 3))
sum((x - 0) ^ 3) / (length(x) * 4.049691 ^ 3)
sum((x - mean(x)) ^ 4) / (length(x) * (sqrt((sum((x - mean(x)) ^ 2) / length(x))) ^ 4)) - 3
sum((x - 0) ^ 4) / (length(x) * 4.049691 ^ 4) - 3
(-2 - 0) / 4.049691
```

```{r}
(0.01 * 0.4) / ((0.02 * 0.6) + (0.01 * 0.4))
```

```{r}
2^3
0.5 * 0.5 * 0.5
```

```{r}
sum((1/8 * -10), (3/8 * -20), (3/8 * 10), (1/8 * 40))
```

```{r}
for(i in 10000) {
  print(i)
}
```

```{r}
webpage <- read_html("https://www.state.gov/foreign-language-training/")
tbls_ls <- webpage %>%
        html_nodes("table") %>%
        html_table(fill = TRUE)

language_data <- as_tibble(data.frame(tbls_ls[4])) %>%
  gather(column, language) %>%
  select(language)

language_vector <- c(language_data, recursive = TRUE) %>%
  unname()

cat(paste(language_vector, collapse=", "))
```

```{r}
factorial(8)/(factorial(5) * factorial(3))
```

```{r}
factorial(15) / (factorial(3) * factorial(12))
ncol(combn(15, 3))
```

```{r}
factorial(100)
```

```{r}
factorial(20) / (factorial(19) * factorial(1))
```

```{r}
binom.test(7, 10, 0.5, alternative = "greater")

dbinom(7, 10, 0.5) + dbinom(8, 10, 0.5) + dbinom(9, 10, 0.5) + dbinom(10, 10, 0.5)

pbinom(3, 10, 0.5, lower.tail = TRUE)

(ncol(combn(10, 7)) * (0.5 ^ 7) * (0.5 ^ 3)) + (ncol(combn(10, 8)) * (0.5 ^ 8) * (0.5 ^ 2)) + (ncol(combn(10, 9)) * (0.5 ^ 9) * (0.5 ^ 1)) + (ncol(combn(10, 10)) * (0.5 ^ 10) * (0.5 ^ 0))
```

```{r}
test_ <- array()
for(i in c(0.05, 0.25, 0.50, 0.75, 0.85, 0.90, 0.95, 0.99)) {
    test_ <-
      append(test_, 
        pwr.p.test(h = ES.h(p1 = 0.55, p2 = 0.5),
               sig.level = 0.01,
               power = i,
               alternative = "greater")
      )
}
```

```{r}
typeof(test_)
```

```{r}
test_ <-
  pwr.p.test(h = ES.h(p1 = 0.55, p2 = 0.5),
             sig.level = 0.01,
             power = .95,
             alternative = "greater")
```

```{r}
plot(test_)
```

```{r}
binom.test(5, 15, 0.125, alternative = "greater")

ncol(combn(15, 5)) * (0.125 ^ 15) * (0.875 ^ 10)
```

```{r}
ncol(combn(10, 2))

```

```{r}
factorial(10) / factorial(7)
```

```{r}
factorial(10) / (factorial(7) * factorial(3))
```

```{r}
mean(rbinom(100, size = 1, prob = 0.5))
```

```{r}
binom.test(65, 100, 0.5, alternative = "greater")

pbinom(35, 100, 0.5, lower.tail = TRUE)


```

```{r}
binom.test(2, 10, (1/6), alternative = "less")

pbinom(2, 10, (1/6), lower.tail = TRUE)

(ncol(combn(10, 0)) * ((1/6) ^ 0) * ((5/6) ^ 10)) + (ncol(combn(10, 1)) * ((1/6) ^ 1) * ((5/6) ^ 9)) + (ncol(combn(10, 2)) * ((1/6) ^ 2) * ((5/6) ^ 8))

```

```{r}
binom.test(7, 10, 0.5, alternative = "greater")

dbinom(7, 10, 0.5) + dbinom(8, 10, 0.5) + dbinom(9, 10, 0.5) + dbinom(10, 10, 0.5)

pbinom(3, 10, 0.5, lower.tail = TRUE)

(ncol(combn(10, 7)) * (0.5 ^ 7) * (0.5 ^ 3)) + (ncol(combn(10, 8)) * (0.5 ^ 8) * (0.5 ^ 2)) + (ncol(combn(10, 9)) * (0.5 ^ 9) * (0.5 ^ 1)) + (ncol(combn(10, 10)) * (0.5 ^ 10) * (0.5 ^ 0))
```

```{r}
binom.test(5, 6, 0.25, alternative = "greater")

(ncol(combn(6, 5)) * (0.25 ^ 5) * (0.75 ^ 1)) + (ncol(combn(6, 6)) * (0.25 ^ 6) * (0.75 ^ 0)) 
```

```{r}
pnorm(75, mean = 74, sd = 1, lower.tail = FALSE)
```

```{r}
factorial(6) / factorial(3)
```

```{r}
factorial(6) / (factorial(3) * factorial(3))

ncol(combn(6, 3))
```

```{r}
1 - ((ncol(combn(8, 6)) * (0.5 ^ 6) * (0.5 ^ 2)) + (ncol(combn(8, 7)) * (0.5 ^ 7) * (0.5 ^ 1)) + (ncol(combn(8, 8)) * (0.5 ^ 8) * (0.5 ^ 0)))
```

```{r}
qnorm(0.7)
```

```{r}
(ncol(combn(8, 5)) * (0.7 ^ 5) * (0.3 ^ 3)) + (ncol(combn(8, 4)) * (0.7 ^ 4) * (0.3 ^ 4)) + (ncol(combn(8, 3)) * (0.7 ^ 3) * (0.3 ^ 5)) + (ncol(combn(8, 2)) * (0.7 ^ 2) * (0.3 ^ 6)) + (ncol(combn(8, 1)) * (0.7 ^ 1) * (0.3 ^ 7)) + (ncol(combn(8, 0)) * (0.7 ^ 0) * (0.3 ^ 8))
```

```{r}
(((15 - 8) ^ 2) / 8) + (((30 - 34) ^ 2) / 34) + (((5 - 8) ^ 2) / 8)
```

```{r}
pnorm(48, 50, 10, lower.tail = TRUE)
```

```{r}
(30 * 20) / 75

```

```{r}
((8 - 4.4) ^ 2) / 4.4
```

```{r}
(28 * 34) / 68
```

```{r}
(80 * 4) + (76 * 6)
```

```{r}
776 / 10
```

```{r}
1.645 * (sqrt(1 / (7 - 3)))
```

```{r}
0.67 - 0.8225
0.67 + 0.8225
```

```{r}
-0.1525 * 2
1.4925 * 2
```

```{r}
0.5 * (log(1 + .25) - log(1 - .25))
```

```{r}
(0.36 / (1 - 0.36)) * (18 - 2)
```

```{r}
sum(c(10 * 0.2, 8.5 * 0.2, 8 * 0.2, 9.5 * 0.2, 10 * 0.2, 10 * 0.2, 9.5 * 0.2, 10 * 0.2, 7.5 * 0.2))
```

```{r}
mean(c(95 * 0.8, 92 * 0.8, 100 * 0.8))
```

```{r}
mean(c(3, 6, 7, 5, 2, 1))

sum(c(1, 4, 9, 1, 4, 9))

mean(c(4, 6, 6, 4, 3, 1))

sum(c(0, 4, 4, 0, 1, 9))

sum(c(12, 36, 42, 20, 8, 9))

sqrt((28 * 18))

21 / sqrt((28 * 18))

((0.94 ^ 2) / (1 - (0.94 ^ 2))) * (6 - 2)

```

```{r}
pct_change <- function(x1, x2) {
  (x2 - x1) / x1
}
```

```{r}
pct_change(1104, 456)
```

```{r}
size <- c(14, 18, 14, 10)
behavior <- c(74, 82, 74, 70)

mean(behavior)

.9409 / (1 - .9409) * (2)
```

```{r}
sqrt(13 * 9)
sqrt(13 * 25)

sqrt(13 * 9) * sqrt(13 * 25)

156 / (sqrt(13 * 9) * sqrt(13 * 25))

(156 / (13 * 9) * (13 * 25)) ^ 2

(0.64 / (1 - 0.64)) * (11)

(0.64 / (1 - 0.64)) * (11) > 4.84

(0.64 / (1 - 0.64)) * (11) > 9.65

```
















